/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as LoginRouteImport } from './routes/login'
import { Route as DashboardRouteImport } from './routes/_dashboard'
import { Route as DashboardIndexRouteImport } from './routes/_dashboard.index'
import { Route as DashboardSettingsRouteImport } from './routes/_dashboard.settings'
import { Route as DashboardRequestsRouteImport } from './routes/_dashboard.requests'
import { Route as DashboardReportsRouteImport } from './routes/_dashboard.reports'
import { Route as DashboardPresenceRouteImport } from './routes/_dashboard.presence'
import { Route as DashboardEmployeesRouteImport } from './routes/_dashboard.employees'
import { Route as DashboardAlertsRouteImport } from './routes/_dashboard.alerts'
import { Route as DashboardAdminRouteImport } from './routes/_dashboard.admin'

const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardRoute = DashboardRouteImport.update({
  id: '/_dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardIndexRoute = DashboardIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardSettingsRoute = DashboardSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardRequestsRoute = DashboardRequestsRouteImport.update({
  id: '/requests',
  path: '/requests',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardReportsRoute = DashboardReportsRouteImport.update({
  id: '/reports',
  path: '/reports',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardPresenceRoute = DashboardPresenceRouteImport.update({
  id: '/presence',
  path: '/presence',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardEmployeesRoute = DashboardEmployeesRouteImport.update({
  id: '/employees',
  path: '/employees',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardAlertsRoute = DashboardAlertsRouteImport.update({
  id: '/alerts',
  path: '/alerts',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardAdminRoute = DashboardAdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => DashboardRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof DashboardIndexRoute
  '/login': typeof LoginRoute
  '/admin': typeof DashboardAdminRoute
  '/alerts': typeof DashboardAlertsRoute
  '/employees': typeof DashboardEmployeesRoute
  '/presence': typeof DashboardPresenceRoute
  '/reports': typeof DashboardReportsRoute
  '/requests': typeof DashboardRequestsRoute
  '/settings': typeof DashboardSettingsRoute
}
export interface FileRoutesByTo {
  '/login': typeof LoginRoute
  '/admin': typeof DashboardAdminRoute
  '/alerts': typeof DashboardAlertsRoute
  '/employees': typeof DashboardEmployeesRoute
  '/presence': typeof DashboardPresenceRoute
  '/reports': typeof DashboardReportsRoute
  '/requests': typeof DashboardRequestsRoute
  '/settings': typeof DashboardSettingsRoute
  '/': typeof DashboardIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_dashboard': typeof DashboardRouteWithChildren
  '/login': typeof LoginRoute
  '/_dashboard/admin': typeof DashboardAdminRoute
  '/_dashboard/alerts': typeof DashboardAlertsRoute
  '/_dashboard/employees': typeof DashboardEmployeesRoute
  '/_dashboard/presence': typeof DashboardPresenceRoute
  '/_dashboard/reports': typeof DashboardReportsRoute
  '/_dashboard/requests': typeof DashboardRequestsRoute
  '/_dashboard/settings': typeof DashboardSettingsRoute
  '/_dashboard/': typeof DashboardIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/login'
    | '/admin'
    | '/alerts'
    | '/employees'
    | '/presence'
    | '/reports'
    | '/requests'
    | '/settings'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/login'
    | '/admin'
    | '/alerts'
    | '/employees'
    | '/presence'
    | '/reports'
    | '/requests'
    | '/settings'
    | '/'
  id:
    | '__root__'
    | '/_dashboard'
    | '/login'
    | '/_dashboard/admin'
    | '/_dashboard/alerts'
    | '/_dashboard/employees'
    | '/_dashboard/presence'
    | '/_dashboard/reports'
    | '/_dashboard/requests'
    | '/_dashboard/settings'
    | '/_dashboard/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  DashboardRoute: typeof DashboardRouteWithChildren
  LoginRoute: typeof LoginRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_dashboard': {
      id: '/_dashboard'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof DashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_dashboard/': {
      id: '/_dashboard/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof DashboardIndexRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/_dashboard/settings': {
      id: '/_dashboard/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof DashboardSettingsRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/_dashboard/requests': {
      id: '/_dashboard/requests'
      path: '/requests'
      fullPath: '/requests'
      preLoaderRoute: typeof DashboardRequestsRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/_dashboard/reports': {
      id: '/_dashboard/reports'
      path: '/reports'
      fullPath: '/reports'
      preLoaderRoute: typeof DashboardReportsRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/_dashboard/presence': {
      id: '/_dashboard/presence'
      path: '/presence'
      fullPath: '/presence'
      preLoaderRoute: typeof DashboardPresenceRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/_dashboard/employees': {
      id: '/_dashboard/employees'
      path: '/employees'
      fullPath: '/employees'
      preLoaderRoute: typeof DashboardEmployeesRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/_dashboard/alerts': {
      id: '/_dashboard/alerts'
      path: '/alerts'
      fullPath: '/alerts'
      preLoaderRoute: typeof DashboardAlertsRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/_dashboard/admin': {
      id: '/_dashboard/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof DashboardAdminRouteImport
      parentRoute: typeof DashboardRoute
    }
  }
}

interface DashboardRouteChildren {
  DashboardAdminRoute: typeof DashboardAdminRoute
  DashboardAlertsRoute: typeof DashboardAlertsRoute
  DashboardEmployeesRoute: typeof DashboardEmployeesRoute
  DashboardPresenceRoute: typeof DashboardPresenceRoute
  DashboardReportsRoute: typeof DashboardReportsRoute
  DashboardRequestsRoute: typeof DashboardRequestsRoute
  DashboardSettingsRoute: typeof DashboardSettingsRoute
  DashboardIndexRoute: typeof DashboardIndexRoute
}

const DashboardRouteChildren: DashboardRouteChildren = {
  DashboardAdminRoute: DashboardAdminRoute,
  DashboardAlertsRoute: DashboardAlertsRoute,
  DashboardEmployeesRoute: DashboardEmployeesRoute,
  DashboardPresenceRoute: DashboardPresenceRoute,
  DashboardReportsRoute: DashboardReportsRoute,
  DashboardRequestsRoute: DashboardRequestsRoute,
  DashboardSettingsRoute: DashboardSettingsRoute,
  DashboardIndexRoute: DashboardIndexRoute,
}

const DashboardRouteWithChildren = DashboardRoute._addFileChildren(
  DashboardRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  DashboardRoute: DashboardRouteWithChildren,
  LoginRoute: LoginRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
